#!name=hostdns
#!desc=手动指定DNS
#!homepage=https://github.com/chideap/MyShadowrocket/main/list/hostdns.module
#!url=https://github.com/chideap/MyShadowrocket/main/list/hostdns.module

[Host]
localhost = 127.0.0.1
ip6-localhost = ::1
ip6-loopback = ::1

#加密dns
dns.google = 8.8.8.8, 8.8.4.4, 2001:4860:4860::8888, 2001:4860:4860::8844 // https://dns.google/dns-query
dns64.dns.google = 2001:4860:4860::6464, 2001:4860:4860::64 // https://dns64.dns.google/dns-query
cloudflare-dns.com = 104.16.249.249, 104.16.248.249, 2606:4700::6810:f8f9, 2606:4700::6810:f9f9 // https://cloudflare-dns.com/dns-query
1dot1dot1dot1.cloudflare-dns.com = 1.1.1.1, 1.0.0.1, 2606:4700:4700::1001, 2606:4700:4700::1111 // 1dot1dot1dot1.cloudflare-dns.com:853
one.one.one.one = 1.1.1.1, 1.0.0.1, 2606:4700:4700::1001, 2606:4700:4700::1111  // one.one.one.one:853
dns.alidns.com = 223.5.5.5, 223.6.6.6, 2400:3200:baba::1, 2400:3200::1 // https://dns.alidns.com/dns-query
doh.pub = 1.12.12.12, 120.53.53.53 // https://doh.pub/dns-query
dot.pub = 1.12.12.12, 120.53.53.53 // dot.pub:853
doh.360.cn = 23.6.48.18, 112.65.69.15 // https://doh.360.cn/dns-query
dot.360.cn = 101.198.198.198, 101.198.199.200, 101.198.192.33, 112.65.69.15 // dot.360.cn:853
dns.twnic.tw = 101.101.101.101, 2001:de4::101, 2001:de4::102 // https://dns.twnic.tw/dns-query
ordns.he.net = 74.82.42.42, 2001:470:20::2 // https://ordns.he.net/dns-query


#阿里巴巴
*.alibaba.cn = server:https://dns.alidns.com/dns-query // 阿里巴巴
*.alibaba.com.cn = server:https://dns.alidns.com/dns-query // 阿里巴巴
*.china.alibaba.com = server:https://dns.alidns.com/dns-query // Alibaba 中国
*.1688.com = server:https://dns.alidns.com/dns-query // 1688
*.taobao.com = server:https://dns.alidns.com/dns-query // 淘宝
*.tbcache.com = server:https://dns.alidns.com/dns-query // 淘宝 缓存
*.tmall.com = server:https://dns.alidns.com/dns-query // 天猫
*.alicdn.com = server:https://dns.alidns.com/dns-query // 阿里 CDN
*.alikunlun.com = server:https://dns.alidns.com/dns-query // 阿里昆仑
*.aliapp.com = server:https://dns.alidns.com/dns-query // 云引擎应用平台
*.aliapp.org = server:https://dns.alidns.com/dns-query // 上云平台
*.alibabausercontent.com = server:https://dns.alidns.com/dns-query // 阿里用户上传资料
*.mmstat.com = server:https://dns.alidns.com/dns-query // mmstat 数据统计 广告追踪
tb.cn = server:https://dns.alidns.com/dns-query // 淘宝短网址

#阿里云
*.aliyun.* = server:https://dns.alidns.com/dns-query // 阿里云
*.aliyuncdn.* = server:https://dns.alidns.com/dns-query // 阿里云 CDN
*.aliyuncs.com = server:https://dns.alidns.com/dns-query // 阿里云 API 服务
*.aliyunddos????.com = server:https://dns.alidns.com/dns-query // 阿里云 DDoS防护
*.aliyundrive.com = server:https://dns.alidns.com/dns-query // 阿里云盘
*.aliyundun.com = server:https://dns.alidns.com/dns-query // 阿里云盾
*.aliyundunwaf.com = server:https://dns.alidns.com/dns-query // 阿里云盾 Web 应用防火墙
*.aliyun-inc.com = server:https://dns.alidns.com/dns-query // 阿里云 内部

#蚂蚁集团
*.antgroup.com = server:https://dns.alidns.com/dns-query // 蚂蚁集团
*.antfin.com = server:https://dns.alidns.com/dns-query // 蚂蚁金服
*.antfinancial.com = server:https://dns.alidns.com/dns-query // 蚂蚁金服
*.alipay.com = server:https://dns.alidns.com/dns-query // 支付宝
*.alipay.com.cn = server:https://dns.alidns.com/dns-query // 支付宝
*.alipaydns.com = server:https://dns.alidns.com/dns-query // 支付宝 HTTP DNS
*.alipayeshop.com = server:https://dns.alidns.com/dns-query // 支付宝 商家资源
*.alipaylog.com = server:https://dns.alidns.com/dns-query // 支付宝 Mdap
*.alipayobjects.com = server:https://dns.alidns.com/dns-query // 支付宝 静态资源
*.alipay-eco.com = server:https://dns.alidns.com/dns-query // 支付宝 开放技术生态体系

#腾讯
*.tencent.com = server:https://doh.pub/dns-query // 腾讯
*.qcloud.com = server:https://doh.pub/dns-query // 腾讯云
*.qcloudcdn.cn = server:https://doh.pub/dns-query // 腾讯云CDN
*.qcloudcdn.com = server:https://doh.pub/dns-query // 腾讯云CDN
*.qcloudcos.com = server:https://doh.pub/dns-query // 腾讯云对象储存
*.qcloudimg.com = server:https://doh.pub/dns-query // 腾讯云静态资源
*.qcloudcjgj.com = server:https://doh.pub/dns-query // 腾讯云超级管家
*.qcloudwzgj.com = server:https://doh.pub/dns-query // 腾讯云网站管家
*.qcloudzygj.com = server:https://doh.pub/dns-query // 腾讯云主页管家
*.myqcloud.com = server:https://doh.pub/dns-query // 腾讯开放云
*.tencent-cloud.net = server:https://doh.pub/dns-query // 腾讯云
*.tencentcloud-aiot.com = server:https://doh.pub/dns-query // 腾讯云aiot解决方案
*.tencentcloudapi.com = server:https://doh.pub/dns-query // 腾讯云API
*.tencentcloudcr.com = server:https://doh.pub/dns-query // 腾讯云容器镜像服务TCR
*.tencentcloudmarket.com = server:https://doh.pub/dns-query // 腾讯云云市场
*.qq.com = server:https://doh.pub/dns-query // QQ
*.qlogo.cn = server:https://doh.pub/dns-query // 腾讯头像
*.qpic.cn = server:https://doh.pub/dns-query // 腾讯图片
*.weixin.qq.com = server:https://doh.pub/dns-query // 微信
*.wx.qq.com = server:https://doh.pub/dns-query // 微信
*.weixin.com = server:https://doh.pub/dns-query // 微信
*.weixinbridge.com = server:https://doh.pub/dns-query // 微信公众平台
*.wechat.com = server:https://doh.pub/dns-query // WeChat
*.servicewechat.com = server:https://doh.pub/dns-query // 微信小程序
*.weiyun.com = server:https://doh.pub/dns-query // 微云
*.gtimg.cn = server:https://doh.pub/dns-query // 腾讯 图片 静态资源
*.idqqimg.com = server:https://doh.pub/dns-query // 腾讯 图片 静态资源
*.cdn-go.cn = server:https://doh.pub/dns-query // 腾讯 静态资源 CDN
*.smtcdns.com = server:https://doh.pub/dns-query // 腾讯云 智能云解析DNS
*.smtcdns.net = server:https://doh.pub/dns-query // 腾讯云 智能云解析DNS
url.cn = server:https://doh.pub/dns-query // 腾讯短网址

#百度
*.baidu = server:180.76.76.76 // 百度
*.baidu.com = server:180.76.76.76 // 百度
*.bdimg.com = server:180.76.76.76 // 百度 静态资源
*.bdstatic.com = server:180.76.76.76 // 百度 静态资源
*.baidupcs.* = server:180.76.76.76 // 百度网盘
*.baiduyuncdn.* = server:180.76.76.76 // 百度云CDN
*.baiduyundns.* = server:180.76.76.76 // 百度云DNS
*.bdydns.* = server:180.76.76.76 // 百度云 DNS
*.bdycdn.* = server:180.76.76.76 // 百度云 CDN
*.bdysite.com = server:180.76.76.76 // 百度云 域名
*.bdysites.com = server:180.76.76.76 // 百度云 域名
*.baidubce.* = server:180.76.76.76 // 百度智能云
*.bcedns.* = server:180.76.76.76 // 百度智能云 DNS
*.bcebos.com = server:180.76.76.76 // 百度智能云 对象存储BOS
*.bcevod.com = server:180.76.76.76 // 百度智能云 播放器服务
*.bceimg.com = server:180.76.76.76 // 百度智能云 图片服务
*.bcehost.com = server:180.76.76.76 // 百度智能云 主机
*.bcehosts.com = server:180.76.76.76 // 百度智能云 主机
dwz.cn = server:180.76.76.76 // 百度短网址

#360
*.360.cn = server:https://doh.360.cn/dns-query // 360安全中心
*.360safe.com = server:https://doh.360.cn/dns-query // 360安全卫士
*.360kuai.com = server:https://doh.360.cn/dns-query // 360快资讯
*.so.com = server:https://doh.360.cn/dns-query // 360搜索
*.360webcache.com = server:https://doh.360.cn/dns-query // 360网页快照服务
*.qihuapi.com = server:https://doh.360.cn/dns-query // 奇虎api
*.qhimg.com = server:https://doh.360.cn/dns-query // 360图床
*.qhimgs.com = server:https://doh.360.cn/dns-query // 360图床
*.qhimgs?.com = server:https://doh.360.cn/dns-query // 360图床
*.qhmsg.com = server:https://doh.360.cn/dns-query // 360
*.qhres.com = server:https://doh.360.cn/dns-query // 奇虎静态资源
*.qhres?.com = server:https://doh.360.cn/dns-query // 奇虎静态资源
*.dhrest.com = server:https://doh.360.cn/dns-query // 导航静态文件
*.qhupdate.com = server:https://doh.360.cn/dns-query // 360
*.yunpan.cn = server:https://doh.360.cn/dns-query // 360安全云盘
*.yunpan.com.cn = server:https://doh.360.cn/dns-query // 360安全云盘
*.yunpan.com = server:https://doh.360.cn/dns-query // 360安全云盘
urlqh.cn = server:https://doh.360.cn/dns-query // 360短网址

#BiliBili
*.bilibili.com = server:system // BiliBili
*.biliapi.com = server:system // BiliBili API
*.biliapi.net = server:system // BiliBili API
*.bilicdn?.com = server:system // BiliBili CDN
*.hdslb.com = server:system // BiliBili 静态资源
*.hdslb.net = server:system // BiliBili 静态资源
cn-hk-eq-bcache-??.bilivideo.com = server:system // BiliBili 视频服务器（unknown）
upos-hz-mirrorakam.akamaized.net = server:system // BiliBili upos视频服务器（akamai）
upos-sz-mirrorasiaov.bilibilivideo.com = server:system // BiliBili upos视频服务器（asia-abroad.com）
upos-sz-mirrorali.bilivideo.com = server:https://dns.alidns.com/dns-query // BiliBili upos视频服务器（阿里云）
upos-sz-mirrorali?.bilivideo.com = server:https://dns.alidns.com/dns-query // BiliBili upos视频服务器（阿里云）
upos-sz-mirrorali??.bilivideo.com = server:https://dns.alidns.com/dns-query // BiliBili upos视频服务器（阿里云）
upos-sz-mirrorbos.bilivideo.com = server:180.76.76.76 // BiliBili upos视频服务器（百度云）
upos-sz-mirrorcos.bilivideo.com = server:https://doh.pub/dns-query // BiliBili upos视频服务器（腾讯云）
upos-sz-mirrorcos?.bilivideo.com = server:https://doh.pub/dns-query // BiliBili upos视频服务器（腾讯云）
upos-sz-mirrorcos??.bilivideo.com = server:https://doh.pub/dns-query // BiliBili upos视频服务器（腾讯云）
upos-sz-mirrorhw.bilivideo.com = server:system // BiliBili upos视频服务器（华为云）
upos-sz-mirrorhw?.bilivideo.com = server:system // BiliBili upos视频服务器（华为云）
upos-sz-mirrorhwo?.bilivideo.com = server:system // BiliBili upos视频服务器（华为云）
upos-sz-mirrorks3.bilivideo.com = server:system // BiliBili upos视频服务器（金山云）
upos-sz-mirrorks3?.bilivideo.com = server:system // BiliBili upos视频服务器（金山云）
upos-sz-mirrorkodo.bilivideo.com = server:system // BiliBili upos视频服务器（七牛云）
upos-sz-mirrorkodo?.bilivideo.com = server:system // BiliBili upos视频服务器（七牛云）
upos-sz-mirrorwcs.bilivideo.com = server:system // BiliBili upos视频服务器（网宿）
upos-sz-mirrorwcs?.bilivideo.com = server:system // BiliBili upos视频服务器（网宿）
upos-sz-mirrorxycdn.bilivideo.com = server:system // BiliBili upos视频服务器（迅雷）
upos-sz-upcdnbd??.bilivideo.com = server:180.76.76.76 // BiliBili upos视频服务器（百度云）
upos-sz-upcdnhw.bilivideo.com = server:system // BiliBili uupos视频服务器（华为云）
upos-sz-upcdntx.bilivideo.com = server:https://doh.pub/dns-query // BiliBili upos视频服务器（腾讯云）
upos-sz-upcdnws.bilivideo.com = server:system // BiliBili upos视频服务器（网宿）
upos-tf-all-js.bilivideo.com = server:system // BiliBili upos视频服务器（unknown）
*.mcdn.bilivideo.com = server:system // BiliBili mCDN视频服务器
*.bilivideo.com = server:system // BiliBili 视频
*.bilivideo.cn = server:system // BiliBili 视频
acg.tv = server:system // BiliBili短网址

#京东
*.jd.com = server:system // 京东
*.360buyimg.com = server:system // 京东 静态资源
*.jdcloud.com = server:system // 京东云
*.jcloudstatic.com = server:system // 京东云 缓存和存储
*.jcloudstatic.net = server:system // 京东云 静态资源
*.jdgslb.com = server:system // 京东云 全局负载均衡
3.cn = server:system // 京东短网址

hdslb.com = server:119.29.29.29
163.com = server:119.29.29.29
*.163.com = server:119.29.29.29
126.com = server:119.29.29.29
*.126.com = server:119.29.29.29
*.126.net = server:119.29.29.29
*.127.net = server:119.29.29.29
*.netease.com = server:119.29.29.29
mi.com = server:119.29.29.29
*.mi.com = server:119.29.29.29
xiaomi.com = server:119.29.29.29
*.xiaomi.com = server:119.29.29.29
routerlogin.net = server:system
_hotspot_.m2m = server:system
router.asus.com = server:system
hotspot.cslwifi.com = server:system
amplifi.lan = server:system
*.lan = server:system
